name: ci 
on:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # mkdocs-blogging-plugin 给出的渲染问题解决方案
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install mkdocs-blogging-plugin
      - run: pip install git+https://github.com/fmaida/hello-dolly-mkdocs-plugin
      - run: pip install git+https://github.com/srymh/MkdocsTagPlugin
      - run: pip install mkdocs-git-revision-date-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-rss-plugin
      - run: pip install mkdocs-print-site-plugin
      - run: pip install mkdocs-tooltips
      - run: pip install mkdocs-categories-plugin
      - run: git push -f git@github.com:Haixiang6123/first-page.git master
      # mkdocs gh-deploy --force
